# Generated by Django 5.2.9 on 2025-12-17 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigWebsite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50, verbose_name='Título da Configuração')),
                ('cor_destaque', models.CharField(default='#DE1E3E', help_text='Selecione uma cor destaque (ex: #DE1E3E).', max_length=7, verbose_name='Cor do título')),
                ('logo', models.FileField(upload_to='imagensConfiguracaoWebsite/', verbose_name='Logotipo')),
                ('favicon', models.FileField(upload_to='imagensConfiguracaoWebsite/', verbose_name='Favicon')),
                ('active', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Configuração do Website',
                'verbose_name_plural': 'Configurações do Website',
                'ordering': ['titulo'],
            },
        ),
    ]
