# Generated by Django 5.2.9 on 2025-12-22 18:52

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_nivelavaria_tipo_unidade'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='nivelavaria',
            options={'ordering': ['nome']},
        ),
        migrations.AlterModelOptions(
            name='tipo',
            options={'ordering': ['nome']},
        ),
        migrations.AlterModelOptions(
            name='unidade',
            options={'ordering': ['codigo']},
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('valor_nota', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor da Nota')),
                ('porcen_desconto', models.DecimalField(decimal_places=2, help_text='Informe um valor entre 0 e 100', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))], verbose_name='Desconto (%)')),
                ('valor_venda', models.DecimalField(decimal_places=2, editable=False, max_digits=10, verbose_name='Valor de Venda')),
                ('nivel_ava_prod', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='produtos', to='website.nivelavaria', verbose_name='Nível de Avaria')),
                ('tipo_prod', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='produtos', to='website.tipo', verbose_name='Tipo')),
                ('unidade_prod', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='produtos', to='website.unidade', verbose_name='Unidade')),
            ],
            options={
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='ProdutoImagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(upload_to='produtos/')),
                ('legenda', models.CharField(blank=True, max_length=120)),
                ('ordem', models.PositiveIntegerField(default=0)),
                ('principal', models.BooleanField(default=False)),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagens', to='website.produto')),
            ],
            options={
                'ordering': ['ordem', 'id'],
            },
        ),
    ]
