# Generated by Django 5.2.9 on 2025-12-24 02:26

import website.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_alter_nivelavaria_options_alter_tipo_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produtoimagem',
            name='imagem',
            field=models.ImageField(upload_to=website.models.upload_to),
        ),
    ]
