# Generated by Django 5.2.9 on 2025-12-24 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_alter_produtoimagem_imagem'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='quantidade',
            field=models.PositiveIntegerField(default=1, help_text='Quantidade em estoque (mínimo 1).', verbose_name='Quantidade'),
        ),
    ]
