# Generated by Django 5.2.9 on 2025-12-24 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_carrinho_carrinhoitem_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrinhoitem',
            name='preco_unitario',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='carrinhoitem',
            name='quantidade',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
