# Generated by Django 5.2.9 on 2025-12-24 20:31

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_formapagamento_venda_vendaitem'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='formapagamento',
            options={'ordering': ['nome']},
        ),
        migrations.AlterModelOptions(
            name='venda',
            options={'ordering': ['-criado_em']},
        ),
        migrations.AlterModelOptions(
            name='vendaitem',
            options={},
        ),
        migrations.AddField(
            model_name='venda',
            name='observacao',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='venda',
            name='status',
            field=models.CharField(choices=[('PENDENTE', 'Pendente'), ('CONFIRMADA', 'Confirmada'), ('CANCELADA', 'Cancelada')], default='PENDENTE', max_length=20),
        ),
        migrations.AlterField(
            model_name='venda',
            name='total',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AlterField(
            model_name='vendaitem',
            name='quantidade',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
