# Generated by Django 5.2.9 on 2025-12-31 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_produto_numero_bo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='numero_bo',
            field=models.IntegerField(verbose_name='Número de BO'),
        ),
    ]
