# Generated by Django 5.2.9 on 2025-12-31 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0012_alter_produto_numero_bo'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='descricao',
            field=models.TextField(default='asdasd', verbose_name='Descrição do produto'),
            preserve_default=False,
        ),
    ]
