# Generated by Django ...

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0013_produto_descricao"),
    ]

    operations = [
        migrations.AddField(
            model_name="carrinhoitem",
            name="atualizado_em",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="carrinhoitem",
            name="criado_em",
            field=models.DateTimeField(default=django.utils.timezone.now, auto_now_add=True),
            preserve_default=False,
        ),
    ]
