# Generated by Django 5.2.9 on 2025-12-31 14:41

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0014_carrinhoitem_atualizado_em_carrinhoitem_criado_em'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrinhoitem',
            name='preco_unitario',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
    ]
