# Generated by Django 5.2.9 on 2026-01-21 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0015_alter_carrinhoitem_preco_unitario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='numero_bo',
            field=models.IntegerField(blank=True, null=True, verbose_name='Número do BO'),
        ),
    ]
