# Generated by Django 5.2.9 on 2026-01-29 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0016_alter_produto_numero_bo'),
    ]

    operations = [
        migrations.AddField(
            model_name='formapagamento',
            name='pix_chave',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='formapagamento',
            name='pix_cidade',
            field=models.CharField(blank=True, default='', max_length=60),
        ),
        migrations.AddField(
            model_name='formapagamento',
            name='pix_copia_cola',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='formapagamento',
            name='pix_nome',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='formapagamento',
            name='tipo',
            field=models.CharField(choices=[('PIX', 'Pix'), ('DINHEIRO', 'Dinheiro em espécie'), ('VALE', 'Vale no pagamento')], default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='venda',
            name='comprovante_pix',
            field=models.FileField(blank=True, null=True, upload_to='comprovantes_pix/', verbose_name='Comprovante Pix'),
        ),
        migrations.AlterField(
            model_name='formapagamento',
            name='nome',
            field=models.CharField(max_length=60),
        ),
    ]
