# Generated by Django 5.2.9 on 2026-01-29 03:46
from django.db import migrations, models


def preencher_codigo(apps, schema_editor):
    FormaPagamento = apps.get_model("website", "FormaPagamento")

    for fp in FormaPagamento.objects.all():
        # se já tiver codigo preenchido, não mexe
        if fp.codigo:
            continue

        # mapeia do campo antigo "tipo"
        # (se no seu banco estava "1"/"2"/"3", também cobre)
        if fp.tipo in ("PIX", "1"):
            fp.codigo = "PIX"
        elif fp.tipo in ("DINHEIRO", "2"):
            fp.codigo = "DINHEIRO"
        elif fp.tipo in ("VALE", "3"):
            fp.codigo = "VALE"
        else:
            # fallback: se tiver nome igual, tenta inferir
            n = (fp.nome or "").strip().lower()
            if "pix" in n:
                fp.codigo = "PIX"
            elif "dinheiro" in n:
                fp.codigo = "DINHEIRO"
            elif "vale" in n:
                fp.codigo = "VALE"

        fp.save(update_fields=["codigo"])


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0017_formapagamento_pix_chave_formapagamento_pix_cidade_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='formapagamento',
            options={'ordering': ['codigo']},
        ),

        # 1) adiciona codigo
        migrations.AddField(
            model_name='formapagamento',
            name='codigo',
            field=models.CharField(
                blank=True,
                null=True,
                choices=[('PIX', 'Pix'), ('DINHEIRO', 'Dinheiro em espécie'), ('VALE', 'Vale no pagamento')],
                max_length=20,
                unique=True,
                verbose_name='Forma',
            ),
        ),

        # 2) preenche codigo a partir do tipo antigo
        migrations.RunPython(preencher_codigo, migrations.RunPython.noop),

        # 3) agora sim remove os antigos
        migrations.RemoveField(
            model_name='formapagamento',
            name='nome',
        ),
        migrations.RemoveField(
            model_name='formapagamento',
            name='tipo',
        ),
    ]
