# Generated by Django 5.2.9 on 2026-01-29 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0018_alter_formapagamento_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formapagamento',
            name='codigo',
            field=models.CharField(choices=[('PIX', 'Pix'), ('DINHEIRO', 'Dinheiro em espécie'), ('VALE', 'Vale no pagamento')], max_length=20, unique=True),
        ),
    ]
