# Generated by Django 5.2.9 on 2026-01-29 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0019_alter_formapagamento_codigo'),
    ]

    operations = [
        migrations.AddField(
            model_name='venda',
            name='comprovante_vale',
            field=models.FileField(blank=True, null=True, upload_to='comprovante_vale/', verbose_name='Comprovante Vale'),
        ),
    ]
