# Generated by Django 5.2.9 on 2026-01-31 13:07

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0020_venda_comprovante_vale'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegraParcelamentoVale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_ate', models.DecimalField(decimal_places=2, help_text='Total do pedido até este valor (inclusive).', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Válido até (R$)')),
                ('max_parcelas', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Máx. parcelas')),
                ('forma_pagamento', models.ForeignKey(limit_choices_to={'codigo': 'VALE'}, on_delete=django.db.models.deletion.CASCADE, related_name='regras_parcelamento_vale', to='website.formapagamento')),
            ],
            options={
                'ordering': ['valor_ate'],
                'unique_together': {('forma_pagamento', 'valor_ate')},
            },
        ),
    ]
