# Generated by Django 5.2.9 on 2026-01-31 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0021_regraparcelamentovale'),
    ]

    operations = [
        migrations.AddField(
            model_name='venda',
            name='parcelas',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
