# Generated by Django 5.2.9 on 2026-03-05 03:34

import django.db.models.deletion
import website.models
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0022_venda_parcelas'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parcelas', models.PositiveIntegerField(default=1)),
                ('comprovante_pix', models.FileField(blank=True, null=True, upload_to='comprovantes_pix/', validators=[website.models.validar_comprovante_pix])),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='carrinho',
            options={},
        ),
        migrations.AlterModelOptions(
            name='formapagamento',
            options={},
        ),
        migrations.AlterModelOptions(
            name='regraparcelamentovale',
            options={'ordering': ['minimo']},
        ),
        migrations.AlterModelOptions(
            name='unidade',
            options={'ordering': ['nome']},
        ),
        migrations.AlterModelOptions(
            name='venda',
            options={},
        ),
        migrations.RemoveConstraint(
            model_name='carrinho',
            name='unique_carrinho_aberto_por_usuario',
        ),
        migrations.RenameField(
            model_name='formapagamento',
            old_name='pix_copia_cola',
            new_name='pix_payload',
        ),
        migrations.AlterUniqueTogether(
            name='regraparcelamentovale',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='unidade',
            name='ativa',
        ),
        migrations.RemoveField(
            model_name='unidade',
            name='codigo',
        ),
        migrations.RemoveField(
            model_name='unidade',
            name='filial',
        ),
        migrations.RemoveField(
            model_name='venda',
            name='comprovante_vale',
        ),
        migrations.AddField(
            model_name='regraparcelamentovale',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='regraparcelamentovale',
            name='maximo',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='regraparcelamentovale',
            name='minimo',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='venda',
            name='atualizado_em',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='carrinho',
            name='status',
            field=models.CharField(choices=[('ABERTO', 'Aberto'), ('FECHADO', 'Fechado')], default='ABERTO', max_length=20),
        ),
        migrations.AlterField(
            model_name='carrinho',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='formapagamento',
            name='pix_cidade',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='formapagamento',
            name='pix_nome',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='regraparcelamentovale',
            name='max_parcelas',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='venda',
            name='comprovante_pix',
            field=models.FileField(blank=True, null=True, upload_to='comprovantes_pix/'),
        ),
        migrations.AlterField(
            model_name='venda',
            name='forma_pagamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='website.formapagamento'),
        ),
        migrations.AlterField(
            model_name='venda',
            name='parcelas',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='venda',
            name='status',
            field=models.CharField(choices=[('PENDENTE', 'Pendente'), ('APROVADA', 'Aprovada'), ('CANCELADA', 'Cancelada')], default='PENDENTE', max_length=20),
        ),
        migrations.AlterField(
            model_name='venda',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='vendaitem',
            name='preco_unitario',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AlterField(
            model_name='vendaitem',
            name='produto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='website.produto'),
        ),
        migrations.AlterField(
            model_name='vendaitem',
            name='quantidade',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='vendaitem',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=12),
        ),
        migrations.AddConstraint(
            model_name='carrinho',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'ABERTO')), fields=('usuario',), name='unique_open_cart_per_user'),
        ),
        migrations.AddField(
            model_name='pagamento',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='website.formapagamento'),
        ),
        migrations.AddField(
            model_name='pagamento',
            name='venda',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pagamento', to='website.venda'),
        ),
        migrations.RemoveField(
            model_name='regraparcelamentovale',
            name='forma_pagamento',
        ),
        migrations.RemoveField(
            model_name='regraparcelamentovale',
            name='valor_ate',
        ),
    ]
