# Generated by Django 5.2.9 on 2026-03-05 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0024_venda_comprovante_vale_alter_venda_comprovante_pix_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipo',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
    ]
