# Generated by Django 5.2.9 on 2026-03-23 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0025_tipo_ativo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formapagamento',
            name='codigo',
            field=models.CharField(choices=[('PIX', 'Pix'), ('DINHEIRO', 'Dinheiro em espécie'), ('VALE', 'Vale no pagamento')], max_length=20),
        ),
        migrations.AddConstraint(
            model_name='formapagamento',
            constraint=models.UniqueConstraint(condition=models.Q(('ativa', True), ('codigo', 'PIX')), fields=('codigo',), name='unique_pix_ativo'),
        ),
    ]
