# Generated by Django 5.2.9 on 2026-03-24 17:54

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0027_favorito'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VendaCancelada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('venda_original_id', models.PositiveIntegerField(blank=True, null=True)),
                ('forma_pagamento', models.CharField(choices=[('PIX', 'Pix'), ('DINHEIRO', 'Dinheiro em espécie'), ('VALE', 'Vale no pagamento')], max_length=20)),
                ('total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('parcelas', models.PositiveIntegerField(default=1)),
                ('observacao', models.TextField(blank=True, default='')),
                ('motivo_cancelamento', models.TextField(blank=True, default='')),
                ('criada_em', models.DateTimeField()),
                ('cancelada_em', models.DateTimeField(auto_now_add=True)),
                ('cancelada_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cancelamentos_realizados', to=settings.AUTH_USER_MODEL)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vendas_canceladas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='VendaCanceladaItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('produto_id_original', models.PositiveIntegerField(blank=True, null=True)),
                ('produto_nome', models.CharField(max_length=255)),
                ('quantidade', models.PositiveIntegerField(default=1)),
                ('preco_unitario', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('venda_cancelada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='website.vendacancelada')),
            ],
        ),
    ]
