# Generated by Django 5.2.9 on 2026-03-24 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0028_vendacancelada_vendacanceladaitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendacanceladaitem',
            name='venda_cancelada',
        ),
        migrations.DeleteModel(
            name='VendaCancelada',
        ),
        migrations.DeleteModel(
            name='VendaCanceladaItem',
        ),
    ]
