# Generated by Django 5.2.9 on 2026-03-25 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0029_remove_vendacanceladaitem_venda_cancelada_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='unidade',
            options={'ordering': ['codigo']},
        ),
        migrations.AddField(
            model_name='unidade',
            name='codigo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
