# Generated by Django 5.2.9 on 2026-03-25 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0030_alter_unidade_options_unidade_codigo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unidade',
            name='codigo',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
