# Generated by Django 5.2.9 on 2026-03-25 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0031_alter_unidade_codigo'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='maximo_por_usuario',
            field=models.PositiveIntegerField(default=0, help_text='0 = sem limite por usuário.', verbose_name='Quantidade máxima por usuário'),
        ),
    ]
