# Generated by Django 5.2.9 on 2026-03-25 12:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0032_produto_maximo_por_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendaitem',
            name='produto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='itens_venda', to='website.produto'),
        ),
    ]
