# Generated by Django 5.2.9 on 2026-03-26 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0033_alter_vendaitem_produto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='numero_bo',
        ),
        migrations.AddField(
            model_name='produto',
            name='minuta',
            field=models.CharField(blank=True, null=True, verbose_name='Minuta de envio'),
        ),
    ]
