# Generated by Django 5.2.9 on 2026-03-26 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0034_remove_produto_numero_bo_produto_minuta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='minuta',
        ),
        migrations.AddField(
            model_name='venda',
            name='minuta',
            field=models.CharField(blank=True, null=True, verbose_name='Minuta de envio'),
        ),
    ]
