# Generated by Django 5.2.9 on 2026-03-26 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0035_remove_produto_minuta_venda_minuta'),
    ]

    operations = [
        migrations.AddField(
            model_name='configwebsite',
            name='image_auth',
            field=models.FileField(default='1', upload_to='imagensConfiguracaoWebsite/', verbose_name='Imagem de Autenticação'),
            preserve_default=False,
        ),
    ]
