# Generated by Django 5.2.9 on 2026-03-26 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0036_configwebsite_image_auth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configwebsite',
            name='image_auth',
            field=models.FileField(blank=True, null=True, upload_to='imagensConfiguracaoWebsite/', verbose_name='Imagem de Autenticação'),
        ),
    ]
