# Generated by Django 5.2.9 on 2026-03-29 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0039_produto_ativo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='ativo',
            field=models.BooleanField(default=False, verbose_name='Ativo para venda'),
        ),
    ]
