# Generated by Django 5.2.9 on 2026-04-05 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0041_alter_venda_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='num_controle',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Número de Controle'),
        ),
    ]
