# Generated by Django 5.2.9 on 2026-04-06 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0042_produto_num_controle'),
    ]

    operations = [
        migrations.CreateModel(
            name='BannerConfigWebsite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner', models.ImageField(upload_to='imagensBannersConfiguracaoWebsite/', verbose_name='Banner do Website')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Banner de Configuração do Website',
                'verbose_name_plural': 'Banners de Configuração do Website',
            },
        ),
    ]
