# Generated by Django 5.2.9 on 2026-04-06 23:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0043_bannerconfigwebsite'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bannerconfigwebsite',
            options={'ordering': ['ordem', 'id'], 'verbose_name': 'Banner da Configuração do Website', 'verbose_name_plural': 'Banners da Configuração do Website'},
        ),
        migrations.AddField(
            model_name='bannerconfigwebsite',
            name='ativo',
            field=models.BooleanField(default=True, verbose_name='Ativo'),
        ),
        migrations.AddField(
            model_name='bannerconfigwebsite',
            name='config_website',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='banners', to='website.configwebsite', verbose_name='Configuração do Website'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bannerconfigwebsite',
            name='link',
            field=models.URLField(blank=True, null=True, verbose_name='Link do banner'),
        ),
        migrations.AddField(
            model_name='bannerconfigwebsite',
            name='ordem',
            field=models.PositiveIntegerField(default=0, help_text='Menor valor aparece primeiro no carrossel.', verbose_name='Ordem'),
        ),
        migrations.AddField(
            model_name='bannerconfigwebsite',
            name='subtitulo',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Subtítulo do banner'),
        ),
        migrations.AddField(
            model_name='bannerconfigwebsite',
            name='titulo',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Título do banner'),
        ),
        migrations.AlterField(
            model_name='bannerconfigwebsite',
            name='banner',
            field=models.ImageField(upload_to='imagensBannersConfiguracaoWebsite/', verbose_name='Imagem do Banner'),
        ),
        migrations.AlterField(
            model_name='configwebsite',
            name='favicon',
            field=models.ImageField(upload_to='imagensConfiguracaoWebsite/', verbose_name='Favicon'),
        ),
        migrations.AlterField(
            model_name='configwebsite',
            name='image_auth',
            field=models.ImageField(blank=True, null=True, upload_to='imagensConfiguracaoWebsite/', verbose_name='Imagem de Autenticação'),
        ),
        migrations.AlterField(
            model_name='configwebsite',
            name='logo',
            field=models.ImageField(upload_to='imagensConfiguracaoWebsite/', verbose_name='Logotipo'),
        ),
    ]
