# Generated by Django 5.2.9 on 2026-04-07 23:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0044_alter_bannerconfigwebsite_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProdutoVariacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(choices=[('CALCADO', 'Calçado'), ('ROUPA', 'Roupa'), ('OUTRO', 'Outro')], default='OUTRO', max_length=20, verbose_name='Categoria da variação')),
                ('genero', models.CharField(blank=True, choices=[('MASCULINO', 'Masculino'), ('FEMININO', 'Feminino'), ('UNISSEX', 'Unissex')], max_length=20, null=True, verbose_name='Gênero')),
                ('faixa_etaria', models.CharField(blank=True, choices=[('ADULTO', 'Adulto'), ('INFANTIL', 'Infantil')], max_length=20, null=True, verbose_name='Faixa etária')),
                ('tamanho', models.CharField(blank=True, help_text='Ex.: P, M, G, GG, 34, 35, 36, 37...', max_length=20, null=True, verbose_name='Tamanho')),
                ('quantidade', models.PositiveIntegerField(default=0, verbose_name='Estoque da variação')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativa')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variacoes', to='website.produto', verbose_name='Produto')),
            ],
            options={
                'ordering': ['categoria', 'genero', 'faixa_etaria', 'tamanho', 'id'],
                'constraints': [models.UniqueConstraint(fields=('produto', 'categoria', 'genero', 'faixa_etaria', 'tamanho'), name='unique_produto_variacao')],
            },
        ),
    ]
