# Generated by Django 5.2.9 on 2026-04-09 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0045_produtovariacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='usa_variacoes',
            field=models.BooleanField(default=False, help_text='Marque para produtos como roupa e calçado, cujo estoque é controlado por variações.', verbose_name='Usa variações'),
        ),
    ]
