# Generated by Django 5.2.9 on 2026-04-09 03:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0046_produto_usa_variacoes'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='carrinhoitem',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='carrinhoitem',
            name='variacao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='itens_carrinho', to='website.produtovariacao'),
        ),
        migrations.AddField(
            model_name='vendaitem',
            name='variacao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='itens_venda', to='website.produtovariacao'),
        ),
        migrations.AddConstraint(
            model_name='carrinhoitem',
            constraint=models.UniqueConstraint(fields=('carrinho', 'produto', 'variacao'), name='unique_cart_product_variation'),
        ),
    ]
