# Generated by Django 5.2.9 on 2026-04-09 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0047_alter_carrinhoitem_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='produtovariacao',
            options={'ordering': ['categoria', 'genero', 'faixa_etaria', 'tamanho', 'cor', 'id']},
        ),
        migrations.RemoveConstraint(
            model_name='produtovariacao',
            name='unique_produto_variacao',
        ),
        migrations.AddField(
            model_name='produtovariacao',
            name='cor',
            field=models.CharField(blank=True, help_text='Ex.: Preto, Branco, Azul Marinho...', max_length=50, null=True, verbose_name='Cor'),
        ),
        migrations.AddConstraint(
            model_name='produtovariacao',
            constraint=models.UniqueConstraint(fields=('produto', 'categoria', 'genero', 'faixa_etaria', 'tamanho', 'cor'), name='unique_produto_variacao'),
        ),
    ]
