# Generated by Django 5.2.9 on 2026-04-10 15:54

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0048_alter_produtovariacao_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='unidade',
            options={'ordering': ['codigo', 'nome']},
        ),
        migrations.AlterField(
            model_name='bannerconfigwebsite',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='bannerconfigwebsite',
            name='banner',
            field=models.ImageField(upload_to='imagensBannersConfiguracaoWebsite/'),
        ),
        migrations.AlterField(
            model_name='bannerconfigwebsite',
            name='config_website',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='banners', to='website.configwebsite'),
        ),
        migrations.AlterField(
            model_name='bannerconfigwebsite',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bannerconfigwebsite',
            name='ordem',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='bannerconfigwebsite',
            name='subtitulo',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='bannerconfigwebsite',
            name='titulo',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='configwebsite',
            name='cor_destaque',
            field=models.CharField(default='#DE1E3E', max_length=7, verbose_name='Cor do título'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='ativo',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='produto',
            name='descricao',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='produto',
            name='maximo_por_usuario',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='produto',
            name='nivel_ava_prod',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='produtos', to='website.nivelavaria'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='num_controle',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='produto',
            name='porcen_desconto',
            field=models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))]),
        ),
        migrations.AlterField(
            model_name='produto',
            name='quantidade',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='produto',
            name='tipo_prod',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='produtos', to='website.tipo'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='unidade_prod',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='produtos', to='website.unidade'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='usa_variacoes',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='produto',
            name='valor_nota',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='produto',
            name='valor_venda',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=10),
        ),
        migrations.AlterField(
            model_name='produtovariacao',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='produtovariacao',
            name='categoria',
            field=models.CharField(choices=[('CALCADO', 'Calçado'), ('ROUPA', 'Roupa'), ('OUTRO', 'Outro')], default='OUTRO', max_length=20),
        ),
        migrations.AlterField(
            model_name='produtovariacao',
            name='cor',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='produtovariacao',
            name='faixa_etaria',
            field=models.CharField(blank=True, choices=[('ADULTO', 'Adulto'), ('INFANTIL', 'Infantil')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='produtovariacao',
            name='genero',
            field=models.CharField(blank=True, choices=[('MASCULINO', 'Masculino'), ('FEMININO', 'Feminino'), ('UNISSEX', 'Unissex')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='produtovariacao',
            name='produto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variacoes', to='website.produto'),
        ),
        migrations.AlterField(
            model_name='produtovariacao',
            name='quantidade',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='produtovariacao',
            name='tamanho',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
