# Generated by Django 5.2.9 on 2026-04-14 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0049_alter_unidade_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produtovariacao',
            name='categoria',
            field=models.CharField(choices=[('CALCADO', 'Calçado'), ('ROUPA', 'Roupa'), ('PNEU', 'Pneu'), ('OUTRO', 'Outro')], default='OUTRO', max_length=20),
        ),
        migrations.AlterField(
            model_name='produtovariacao',
            name='faixa_etaria',
            field=models.CharField(blank=True, choices=[('QUALQUER', 'Qualquer'), ('ADULTO', 'Adulto'), ('INFANTIL', 'Infantil')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='produtovariacao',
            name='genero',
            field=models.CharField(blank=True, choices=[('AUTOMOVEIS', 'Automóveis'), ('MASCULINO', 'Masculino'), ('FEMININO', 'Feminino'), ('UNISSEX', 'Unissex')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='produtovariacao',
            name='tamanho',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
