# Generated by Django 5.2.9 on 2025-12-31 11:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('website', '0009_alter_formapagamento_options_alter_venda_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='unidade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='usuarios', to='website.unidade', verbose_name='Unidade'),
        ),
    ]
