# Generated by Django 5.2.9 on 2026-03-25 11:07

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_unidade'),
        ('website', '0030_alter_unidade_options_unidade_codigo'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='cpf',
            field=models.CharField(blank=True, max_length=11, null=True, validators=[django.core.validators.RegexValidator('^[0-9]+$', 'Use apenas números no CPF.')]),
        ),
        migrations.AlterField(
            model_name='user',
            name='numero_cracha',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, validators=[django.core.validators.RegexValidator('^[0-9]+$', 'Use apenas números no crachá.')], verbose_name='Número do crachá'),
        ),
        migrations.AlterField(
            model_name='user',
            name='unidade',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='usuarios', to='website.unidade', verbose_name='Unidade'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=150),
        ),
    ]
