# Generated by Django 5.2.9 on 2026-04-02 03:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='cpf',
            field=models.CharField(default='12345678999', max_length=11, validators=[django.core.validators.RegexValidator('^[0-9]+$', 'Use apenas números no CPF.')]),
            preserve_default=False,
        ),
    ]
