# Generated by Django 5.2.9 on 2026-04-02 03:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_user_cpf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='numero_cracha',
            field=models.CharField(max_length=20, unique=True, validators=[django.core.validators.RegexValidator('^[0-9]+$', 'Use apenas números no crachá.')], verbose_name='Número do crachá'),
        ),
    ]
